In [10]:
import numpy as np

zeros = np.zeros(6)
ones = np.ones(6)

ones

array([1., 1., 1., 1., 1., 1.])

In [3]:
two_dimension = np.zeros((6,7))

two_dimension

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [18]:
A = np.array([(1,2),(3,4)])
B = np.array([(5,6),(7,8)])
C = A.dot(B)

print("C = \n", C)
print("Max Value of C ", C.max())
print("Min Value of C ", C.min())
print("Average Value of C ", C.mean())

C = 
 [[19 22]
 [43 50]]
Max Value of C  50
Min Value of C  19
Average Value of C  33.5
